-- Database Schema for Digital Certificate Verification System

-- 1. Users Table (Admin/Issuers)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT CHECK(role IN ('admin', 'issuer')) DEFAULT 'issuer'
);

-- 2. Certificates Table
CREATE TABLE IF NOT EXISTS certificates (
    cert_id TEXT PRIMARY KEY, -- UUID or Hashed ID
    holder_name TEXT NOT NULL,
    course_name TEXT NOT NULL,
    issuing_authority TEXT NOT NULL,
    issue_date DATE DEFAULT CURRENT_DATE,
    issuer_id INTEGER,
    FOREIGN KEY (issuer_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 3. Verification Logs Table
CREATE TABLE IF NOT EXISTS verification_logs (
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cert_id TEXT, -- Note: Can be NULL if the certificate doesn't exist (invalid attempt)
    attempt_id TEXT, -- For tracking if needed
    verification_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    status TEXT CHECK(status IN ('VALID', 'INVALID')),
    FOREIGN KEY (cert_id) REFERENCES certificates(cert_id) ON DELETE CASCADE
);

-- Indexing for fast search
CREATE INDEX IF NOT EXISTS idx_certificates_cert_id ON certificates(cert_id);
CREATE INDEX IF NOT EXISTS idx_logs_cert_id ON verification_logs(cert_id);

-- Sample Data
INSERT OR IGNORE INTO users (username, password, role) VALUES ('admin', 'admin123', 'admin');
INSERT OR IGNORE INTO users (username, password, role) VALUES ('issuer1', 'issuer123', 'issuer');

-- Sample Certificates (IDs will be generated by code normally, but for demo:)
INSERT OR IGNORE INTO certificates (cert_id, holder_name, course_name, issuing_authority, issuer_id) 
VALUES ('CERT-123-ABC', 'John Doe', 'Full Stack Development', 'Antigravity Academy', 1);

INSERT OR IGNORE INTO certificates (cert_id, holder_name, course_name, issuing_authority, issuer_id) 
VALUES ('CERT-456-DEF', 'Jane Smith', 'Database Management Systems', 'Tech University', 2);
